"""Assemble the final investigation report and render it as JSON, Markdown and Slack Block Kit."""
import json
from datetime import datetime
from pathlib import Path

SEVERITY_EMOJI = {"Critical": ":red_circle:", "High": ":red_circle:", "Medium": ":large_orange_circle:",
                  "Low": ":large_yellow_circle:"}
SOURCE_LABELS = {
    "prometheus": "Prometheus metrics",
    "kubernetes.events": "Kubernetes events",
    "kubernetes.pod_status": "Pod status",
    "kubernetes.pod_journal": "Pod state journal (watch)",
    "kubernetes.replicasets+configmaps": "Deployment/ConfigMap history",
    "logs": "Application logs",
    "detector": "Detector signal",
}


def hms(t) -> str:
    return datetime.fromtimestamp(t).astimezone().strftime("%H:%M:%S") if t else "—"


def dur(s) -> str:
    s = int(s or 0)
    return f"{s // 60}m {s % 60:02d}s" if s >= 60 else f"{s}s"


def build_report(bundle: dict, a: dict, narrative: dict, generator: str) -> dict:
    inc, imp, t = bundle["incident"], a["impact"], a["target"]
    used = {eid for e in a["timeline"] for eid in e["evidence"]} | {
        eid for s in narrative.get("causal_chain", []) for eid in s["evidence"]}
    evidence = [e for e in a["evidence"] if e["id"] in used] or a["evidence"]
    affected = [f"Deployment {t['namespace']}/{t['deployment']}"]
    if t["service"]:
        affected.append(f"Service {t['service']}")
    affected += [f"Pod {p}" for p in imp["affected_pods"]]
    affected += [f"Dependent service {d} (served 5xx to users)" if d == a["entry_app"] else f"Dependent service {d}"
                 for d in imp["dependent_services"]]
    return {
        "id": inc["id"],
        "status": "Investigated" if not imp["ongoing"] else "Investigated (impact ongoing)",
        "severity": a["severity"],
        "title": narrative["title"],
        "namespace": t["namespace"],
        "deployment": t["deployment"],
        "service": t["service"],
        "summary": narrative["summary"],
        "symptom": narrative["symptom"],
        "root_cause": narrative["root_cause"],
        "causal_chain": narrative["causal_chain"],
        "contributing_factors": narrative["contributing_factors"],
        "impact_summary": narrative["impact_summary"],
        "impact": imp,
        "affected_components": affected,
        "timeline": a["timeline"],
        "key_times": a["key_times"],
        "ruled_out": narrative["ruled_out"],
        "confidence": narrative["confidence"],
        "rule_engine_confidence": a["confidence"],
        "confidence_rationale": narrative["confidence_rationale"],
        "recommended_next_steps": narrative["recommended_next_steps"],
        "hypotheses": a["hypotheses"],
        "evidence": evidence,
        "evidence_sources": sorted({e["source"] for e in evidence}),
        "detection": {"detected_at": inc.get("detected_at"), "triggers": inc.get("triggers", [])},
        "window": bundle["window"],
        "generated_by": generator,
        "generated_at": bundle["collected_at"],
    }


def _impact_lines(r: dict) -> list[str]:
    imp = r["impact"]
    lines = [
        f"Impact window: {hms(imp['start_t'])} → {hms(imp['end_t']) if not imp['ongoing'] else 'ongoing'} ({dur(imp['duration_s'])})",
        f"Error rate: peak {imp['peak_error_ratio'] * 100:.1f}%" + (
            f", average {imp['avg_error_ratio'] * 100:.1f}%" if imp["avg_error_ratio"] is not None else "")
        if imp["peak_error_ratio"] is not None else "Error rate: n/a",
        f"Requests: ~{imp['requests_failed']:,} failed of ~{imp['requests_total']:,}"
        + (f" ({', '.join(f'{k}: {v:,}' for k, v in sorted(imp['failed_by_code'].items()))})" if imp["failed_by_code"] else ""),
        f"Pods affected: {len(imp['affected_pods'])}/{imp['pods_total']} — {imp['container_terminations']} container terminations "
        f"({imp['oom_kills']} OOMKilled), min ready replicas {imp['min_ready_replicas']}/{imp['replicas_desired']}",
    ]
    if imp["no_ready_endpoints_s"]:
        lines.append(f"Service had zero ready endpoints for {dur(imp['no_ready_endpoints_s'])}")
    if imp["peak_p95_latency_s"]:
        lines.append(f"Peak p95 latency at {imp['user_facing_service']}: {imp['peak_p95_latency_s'] * 1000:.0f} ms")
    return lines


def render_markdown(r: dict) -> str:
    out = [f"# {r['severity']} — {r['title']}", "",
           f"**Incident:** {r['id']}  |  **Status:** {r['status']}  |  **Severity:** {r['severity']}  |  "
           f"**Confidence:** {r['confidence'] * 100:.0f}%  |  **Generated by:** {r['generated_by']}", "",
           f"**Namespace:** `{r['namespace']}`  **Deployment:** `{r['deployment']}`  **Service:** `{r['service']}`", "",
           "## Summary", r["summary"], "",
           "## Observed symptom", r["symptom"], "",
           "## Root cause", r["root_cause"], "",
           "## Causal chain"]
    out += [f"{i}. {s['step']} _[{', '.join(s['evidence'])}]_" for i, s in enumerate(r["causal_chain"], 1)]
    out += ["", "## Timeline", "", "| Time | Event | Evidence |", "|---|---|---|"]
    out += [f"| {hms(e['t'])} | {e['text']} | {', '.join(e['evidence'])} |" for e in r["timeline"]]
    out += ["", "## Impact", r["impact_summary"], ""] + [f"- {l}" for l in _impact_lines(r)]
    out += ["", "## Affected components"] + [f"- {c}" for c in r["affected_components"]]
    if r["contributing_factors"]:
        out += ["", "## Contributing factors"] + [f"- {c}" for c in r["contributing_factors"]]
    out += ["", "## Hypotheses considered", "", "| Hypothesis | Score | Checks passed |", "|---|---|---|"]
    out += [f"| {h['title']} | {h['score']:.2f} | {sum(c['result'] for c in h['checks'])}/{len(h['checks'])} |"
            for h in r["hypotheses"]]
    if r["ruled_out"]:
        out += ["", "### Ruled out"] + [f"- **{x['hypothesis']}** — {x['reason']}" for x in r["ruled_out"]]
    out += ["", "## Confidence", f"{r['confidence'] * 100:.0f}% (rule engine: {r['rule_engine_confidence'] * 100:.0f}%) — "
            f"{r['confidence_rationale']}"]
    if r["recommended_next_steps"]:
        out += ["", "## Suggested next steps (not executed)"] + [f"- {s}" for s in r["recommended_next_steps"]]
    out += ["", "## Evidence", "", "| ID | Source | Description | Reference |", "|---|---|---|---|"]
    out += [f"| {e['id']} | {e['source']} | {e['title']} | `{e['ref']}` |".replace("\n", " ") for e in r["evidence"]]
    out += ["", f"_Detection: {', '.join(r['detection']['triggers']) or 'manual'} at {hms(r['detection']['detected_at'])}. "
            f"Investigation window {hms(r['window']['start'])}–{hms(r['window']['end'])}._", ""]
    return "\n".join(out)


def _trim(text: str, limit: int = 2900) -> str:
    return text if len(text) <= limit else text[: limit - 20] + "\n… (truncated)"


def slack_payload(r: dict, report_path: str | None = None) -> dict:
    emoji = SEVERITY_EMOJI.get(r["severity"], ":red_circle:")
    service = r["service"] or r["deployment"]
    timeline = [e for e in r["timeline"] if e["kind"] != "log"][:16]
    tl_text = "\n".join(f"• `{hms(e['t'])}` — {e['text']}" for e in timeline)
    chain = "\n".join(f"{i}. {s['step']}" for i, s in enumerate(r["causal_chain"], 1))
    sources = ", ".join(SOURCE_LABELS.get(s, s) for s in r["evidence_sources"])
    blocks = [
        {"type": "header", "text": {"type": "plain_text", "text": f"Kubernetes Incident — {service.title()} Service"[:150], "emoji": True}},
        {"type": "section", "fields": [
            {"type": "mrkdwn", "text": f"*Status:*\n{r['status']}"},
            {"type": "mrkdwn", "text": f"*Severity:*\n{emoji} {r['severity']}"},
            {"type": "mrkdwn", "text": f"*Namespace / Deployment:*\n`{r['namespace']}` / `{r['deployment']}`"},
            {"type": "mrkdwn", "text": f"*Confidence:*\n{r['confidence'] * 100:.0f}%"},
        ]},
        {"type": "section", "text": {"type": "mrkdwn", "text": _trim(f"*Summary:* {r['summary']}")}},
        {"type": "section", "text": {"type": "mrkdwn", "text": _trim(f"*Symptom:* {r['symptom']}")}},
        {"type": "section", "text": {"type": "mrkdwn", "text": _trim(f"*Root Cause:* {r['root_cause']}")}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": _trim(f"*Timeline:*\n{tl_text}")}},
    ]
    if chain:
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": _trim(f"*Causal chain:*\n{chain}")}})
    blocks += [
        {"type": "section", "text": {"type": "mrkdwn", "text": _trim(
            "*Affected Components:*\n" + "\n".join(f"• {c}" for c in r["affected_components"]))}},
        {"type": "section", "text": {"type": "mrkdwn", "text": _trim(
            f"*Impact:* {r['impact_summary']}\n" + "\n".join(f"• {l}" for l in _impact_lines(r)))}},
    ]
    if r["ruled_out"]:
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": _trim(
            "*Ruled out:*\n" + "\n".join(f"• {x['hypothesis']}" for x in r["ruled_out"][:4]))}})
    if r["recommended_next_steps"]:
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": _trim(
            "*Suggested next steps (not executed):*\n" + "\n".join(f"• {s}" for s in r["recommended_next_steps"][:5]))}})
    blocks += [
        {"type": "section", "text": {"type": "mrkdwn", "text": _trim(
            f"*Evidence:* {sources} ({len(r['evidence'])} items)")}},
        {"type": "context", "elements": [{"type": "mrkdwn", "text": _trim(
            f"{r['id']} • detected {hms(r['detection']['detected_at'])} via {', '.join(r['detection']['triggers']) or 'manual trigger'}"
            f" • analysis: {r['generated_by']}" + (f" • full report: `{report_path}`" if report_path else ""), 1900)}]},
    ]
    fallback = f"{r['severity']} incident {r['id']}: {r['summary']}"
    return {"text": fallback, "blocks": blocks}


def detection_payload(incident: dict, namespace: str) -> dict:
    text = (f":large_orange_circle: *Incident detected* — `{namespace}` ({incident['id']})\n"
            f"Triggers: {', '.join(incident['triggers'])}\nInvestigation in progress; report will follow when the incident stabilises.")
    return {"text": f"Incident detected in {namespace}: {', '.join(incident['triggers'])}",
            "blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": text}}]}


def save(report: dict, bundle: dict, analysis: dict, reports_dir: Path) -> dict:
    reports_dir.mkdir(parents=True, exist_ok=True)
    base = reports_dir / report["id"]
    paths = {"markdown": base.with_suffix(".md"), "report": base.with_suffix(".json"),
             "evidence": Path(str(base) + ".evidence.json")}
    paths["markdown"].write_text(render_markdown(report), encoding="utf-8")
    paths["report"].write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
    raw = {"bundle": bundle, "analysis": {k: v for k, v in analysis.items() if not k.startswith("_")}}
    paths["evidence"].write_text(json.dumps(raw, indent=1, default=str), encoding="utf-8")
    return {k: str(v) for k, v in paths.items()}
